app_name: "Space"
instance_name: "single_local"
environment: development
debug: true
log_stack:
  - printer
log_level: debug
sentry_environment: development
translate_files:
  - hexa.en
  - en
  - hexa.fa
  - fa
fallback_languages:
  - en
port: 4000
db:
  driver: postgres
  data_source: postgres://root:12345@localhost/space?sslmode=disable&connect_timeout=10&binary_parameters=yes
  max_open_conns: 300 # unlimited.
  max_idle_conns: 20
  conn_max_idle_time_milliseconds: 300000
  conn_max_lifetime_milliseconds: 3600000 # one hour.
  migrations_statement_timeout_seconds: 100000

probe_server_address: ":11000"
open_telemetry:
  tracing:
    noop_tracer: false # set true to disable jaeger
    jaeger_addr: "http://localhost:14268/api/traces"
    always_sample: true # in production set to false.
  metric:
    enabled: true


echo_log_level: info
allow_origins:
  - "*"
auth_token_cookie:
  name: auth_token
  max_age: 2000
  path: /
  http_only: true
  secure: false
  same_site: none
csrf_cookie:
  name: csrf_token
  max_age: 2000
  path: /
  http_only: true
  secure: false
  same_site: none

redis_address: "127.0.0.1:6379"

cache:
  enabled: true
  redis:
    prefix: sc_ #sc = space cache
    default_ttl_seconds: 1800
