{
 "title": "T3 teams report",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DB", "query": "postgres" },
   {
    "name": "region",
    "label": "Region",
    "query": "select val as region from ticket_labels where key='region' group by val;"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "select val as group\nfrom ticket_labels\nwhere key = 'group'\n  and ticket_id in (select l.ticket_id\n                    from ticket_labels l\n                    where (key = 'region' and val in ($region)))\ngroup by val;"
   },
   {
    "name": "team",
    "label": "Team",
    "query": "select val as team\nfrom ticket_labels\nwhere key = 'team'\n  and ticket_id in (select l.ticket_id\n                    from ticket_labels l\n                    where (key = 'region' and l.val in ($region))\n                    or (key='group' and l.val = '$group')\n                    group by l.ticket_id having count(l.key)=2\n                    )\ngroup by val;"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall: $group ($region)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    count(*) as non_spams,\n    SUM(CASE WHEN severity is null THEN 1 ELSE 0 END)    unspecified_severity,\n    SUM(CASE WHEN severity = 'low' THEN 1 ELSE 0 END)    low_Severity,\n    SUM(CASE WHEN severity = 'medium' THEN 1 ELSE 0 END) medium_severity,\n    SUM(CASE WHEN severity = 'high' THEN 1 ELSE 0 END)   high_severity,\n    avg(tickets.seen_at - tickets.started_at)            mtts,\n    avg(tickets.ended_at - tickets.started_at)           mttr\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'group'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ('region-1','region-2'))\n                or (key = 'group' and val = 'group-d')\n             group by ticket_id\n             having count(key) = 2)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by ticket_labels.val;"
    }
   ]
  },
  {
   "title": "Teams",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n    ticket_labels.val as                                 team,\n    count(*) as non_spams,\n       SUM(CASE WHEN severity is null THEN 1 ELSE 0 END)    unspecified_severity,\n       SUM(CASE WHEN severity = 'low' THEN 1 ELSE 0 END)    low_Severity,\n       SUM(CASE WHEN severity = 'medium' THEN 1 ELSE 0 END) medium_severity,\n       SUM(CASE WHEN severity = 'high' THEN 1 ELSE 0 END)   high_severity,\n       avg(tickets.seen_at - tickets.started_at)            mtts,\n       avg(tickets.ended_at - tickets.started_at)           mttr\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by ticket_labels.val;\n"
    }
   ]
  },
  {
   "title": "Non-spam Tickets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n   $__unixEpochGroup(ended_at/1000,'5h') time,\n    ticket_labels.val as                                 team,\n    count(*) as non_spams\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by time, ticket_labels.val order by time;\n"
    }
   ]
  },
  {
   "title": "Spam Tickets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n   $__unixEpochGroup(ended_at/1000,'5h') time,\n    ticket_labels.val as                                 team,\n    count(*) as spams\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = true\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by time, ticket_labels.val order by time;\n"
    }
   ]
  },
  {
   "title": "Tickets Severity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n   $__unixEpochGroup(ended_at/1000,'5h') time,\n    ticket_labels.val as                                 team,\n       SUM(CASE WHEN severity is null THEN 1 ELSE 0 END)    unspecified,\n       SUM(CASE WHEN severity = 'low' THEN 1 ELSE 0 END)    low,\n       SUM(CASE WHEN severity = 'medium' THEN 1 ELSE 0 END) medium,\n       SUM(CASE WHEN severity = 'high' THEN 1 ELSE 0 END)   high\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by time, ticket_labels.val order by time;\n"
    }
   ]
  },
  {
   "title": "MTTSee by teams Teams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "select\n   $__unixEpochGroup(ended_at/1000,'5h') time,\n    ticket_labels.val as                                 team,\n       avg(tickets.seen_at - tickets.started_at)/1000            MTT_See\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by time, ticket_labels.val order by time;\n"
    }
   ]
  },
  {
   "title": "MTTResolve by teams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "select\n   $__unixEpochGroup(ended_at/1000,'5h') time,\n    ticket_labels.val as                                 team,\n       avg(tickets.ended_at - tickets.started_at)           MTT_Resolve\nfrom tickets\n         join ticket_labels on\n            tickets.id = ticket_labels.ticket_id and\n            ticket_labels.key = 'team'\nwhere is_spam = false\n  and id in (select ticket_id\n             from ticket_labels\n             where (key = 'region' and val in ($region))\n                or (key = 'group' and val = '$group')\n                or (key = 'team' and val in ($team))\n             group by ticket_id\n             having count(key) = 3)\n  and ended_at >=  $__unixEpochFrom()::bigint*1000\n  AND ended_at <= $__unixEpochTo()::bigint *1000\ngroup by time, ticket_labels.val order by time;\n"
    }
   ]
  }
 ]
}