// Code generated by "make app-layers"
// DO NOT EDIT
package sqlstore

import (
	"t3.org/t3/internal/model"
)

var (
	systemColumns      = []string{"name", "value", "created_at", "updated_at"}
	ticketColumns      = []string{"id", "global_fingerprint", "fingerprint", "source", "raw", "annotations", "is_firing", "started_at", "ended_at", "values", "generator_url", "is_spam", "severity", "title", "description", "seen_at", "created_at", "updated_at"}
	ticketLabelColumns = []string{"ticket_id", "key", "val"}
)

func systemFields(m *model.System) []any {
	return []interface{}{&m.Name, &m.Value, &m.CreatedAt, &m.UpdatedAt}
}

func ticketFields(m *model.Ticket) []any {
	return []interface{}{&m.ID, &m.GlobalFingerprint, &m.Fingerprint, &m.Source, &m.Raw, &m.Annotations, &m.IsFiring, &m.StartedAt, &m.EndedAt, &m.Values, &m.GeneratorUrl, &m.IsSpam, &m.Severity, &m.Title, &m.Description, &m.SeenAt, &m.CreatedAt, &m.UpdatedAt}
}

func ticketLabelFields(m *model.TicketLabel) []any {
	return []interface{}{&m.TicketID, &m.Key, &m.Val}
}
