# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.example.com"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db

log_config: "/data/localhost.log.config"
media_store_path: /data/media_store
registration_shared_secret: "2.0bqUzrw~Lxj,6&j8=Gi~,uTDhS:.#~RnbGQNvPHkD#ko*OM@"
report_stats: true
macaroon_secret_key: "HpGICLW*XtTOA2xfB30tJo9OuTVC~1HPsyJ=#S*Lg=*L407GS3"
form_secret: "d&L9XPOAJT_9=Qo=:UL:5HBY5*.QBkq3FUEsn;pMDm8l37tB:G"
signing_key_path: "/data/localhost.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml
