# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.example.com"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/etc/synapse/matrix.example.com.log.config"
media_store_path: /data/media_store
registration_shared_secret: "+#vVK67aSS.Lvk9C5Er14kFd7Wcp,n_Hl;ww9rm#TPWo~EhN0Q"
report_stats: true
macaroon_secret_key: "yYe_f8DUaC.m^;deFiaFjASBL;HUBa5X.K9&Hh@@Rj5BN28Od0"
form_secret: "=lA=4ppqKgLKn0CYYko3VQwa0p8xE7B+QAue7X5UPJ5=9dI4aW"
signing_key_path: "/etc/synapse/matrix.example.com.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml
