name: build

on:
  push:
    branches: [ $default-branch,"wflow" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install libolm
        run: sudo apt-get install -y libolm-dev

      - name: Build
        run: go build -mod=vendor -v ./...

      - name: Test
        run: go test -mod=vendor -v ./...


